name: Auto Deploy

on:
  push:
    branches: [ main ] # Runs only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Change to your Ruby version
      - name: Install Bundler & Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Capistrano Deploy
        run: bundle exec cap production deploy
